title: Jon Saad-Falcon
tagline: Computer Science Ph.D. & MBA Candidate at Stanford University
description: Jon Saad-Falcon is a joint Computer Science Ph.D. and MBA student at Stanford University, advised by Azalia Mirhoseini and Christopher Ré.
url: https://jonsaadfalcon.com
baseurl: ""
# gems: [jekyll-paginate]
# paginate: 5

# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink: "/:title"
# relative_permalinks: true

sass:
  sass_dir: _sass
  style: compressed

author:
  name: Jon Saad-Falcon
  url: https://jonsaadfalcon.com
  email: jonsaadfalcon@stanford.edu

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'syntax'

excerpt_separator: <!--more-->

plugins:
  - jekyll-sitemap
  - jekyll-feed
